- hosts: all
  roles:
#    - { role: nginx, tags: [nginx]}
    - { role: worldpress, tags: [worldpress]}
    - { role: mysql, tags: [mysql]} 
    - { role: fpm, tags: [php]}
    - { role: upgrade, tags: [upgrade]}
    - { role: jira, tags: [jira]}
