all: # группа по умолчанию
  children: # указываем, что это вложенные хосты
    apt:
      hosts:
        192.168.1.7:
          ansible_user: polesyade
        192.168.1.8:
          ansible_user: polesyade
        192.168.1.9:
          ansible_user: polesyade
        192.168.1.2:
          ansible_user: polesyade
